config/routes.rb
Johnforcarlos::Application.routes.draw do
  resources :funds

  resources :pins

  devise_for :users
  get 'home' => 'pages#home'
  get 'messages' => 'pins#index'
  resources :charges

   root 'pages#home'

  

end

app/models/fund.rb
class Fund < ActiveRecord::Base
  attr_accessible :email, :dollars, :name, :paid

  validates :dollars, :numericality => { :greater_than_or_equal_to => 5 }

  validates :name, :presence => :true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
end

app/models/pin.rb
class Pin < ActiveRecord::Base

  attr_accessible :description, :name
  validates :description, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable
         :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = Fund.last.dollars * 100

	  customer = Stripe::Customer.create(
	    :email => Fund.last.email,
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.order("created_at desc").page(params[:page]).per_page(12)
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to new_charge_path }
        format.json { render action: 'show', status: :created, location: @fund }
      else
        format.html { render action: 'new' }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:email, :dollars, :name, :paid)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(5)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Thank you for your message.' }
        format.json { render action: 'home', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/charges/create.html.erb
<% provide(:title, 'Donation Received') %>

<div class="hero-unit">
  <h1><%= yield(:title) %>!</h1>
  <hr>
  <p>
    Dear <%= Fund.last.name %>,
  </p>
  <p>
  	Thank you so much for your donation to John for Carlos! 100% of every dollar donated will be put into a trust fund for Carlos' education, and your donation of $<%= Fund.last.dollars %> is greatly appreciated.
  </p>
  <p>
  	Please save this page for your receipt. Receipt ID # 000<%= Fund.last.id %>.
  </p>
  <p>
  	Thank you, <br>
  	The Iasons
  </p><hr>
<p><%= link_to 'Home', root_path, class: "btn btn-inverse" %></p>
</div>

app/views/charges/new.html.erb
<% provide(:title, 'Confirm Donation') %>

<div class="hero-unit">
<h1><%= yield(:title) %></h1>
<hr>

<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <p>Amount: <%= number_to_currency(Fund.last.dollars) %></p>
      <p>Email: <%= Fund.last.email %></p>
      
    </label>
  </article>
  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Donate to John for Carlos"
          data-amount="<%= Fund.last.dollars * 100 %>"></script>
<% end %>
</div>

app/views/funds/_back.html.erb
<%= link_to '<< Back', root_path, class: "btn btn-inverse" %>

app/views/funds/_form.html.erb
<%= simple_form_for(@fund, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email, label: "Email Address" %>
    <%= f.input :dollars, label: "Donation Amount $"%>
	
	<% if user_signed_in? && current_user.admin? %>
	    <%= f.input :paid, label: "Payment was received", as: :radio_buttons %>
   	<% end %>

  </div>

  <div class="form-actions">
    <%= f.submit "Make Donation", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/funds/_fund.html.erb
<% if fund.paid? %>
  <tr style="color:green">
<% else %>
    <tr>
<% end %>
    <td><%= link_to fund.name, fund %></td>
    <td><%= number_to_currency(fund.dollars) %></td>
    <td>
    	<% t = fund.created_at %>
    	<% t -= (7 * 60 * 60) %>
    	<%= t.strftime("%B %d, %Y @ %I:%M %p") %>
    </td>
    <td><%= link_to "Verify Donation", fund, class: "btn btn-primary" %></td>
    <td>
        <% unless fund.paid? %>
            <%= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
    </td>
  </tr>

app/views/funds/edit.html.erb
<% if user_signed_in? && current_user.admin? %>

<% provide(:title, 'Confirm Donation') %>

<div class="hero-unit">
  <h1><%= yield(:title) %></h1>
  <hr>

<%= render 'form' %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

</div>
<% end %>

app/views/funds/index.html.erb
<% if user_signed_in? && current_user.admin? %>

<% provide(:title, 'Donations Received') %>

<div class="hero-unit">
  <h1>
    Total Donations Received: 
    <% total = 0 %>
    <% Fund.all.each do |x| %>
      <% if x.paid? %>
        <% total += x.dollars %>
      <% end %>
    <% end %>  
    <%= number_to_currency(total) %>
  </h1>
  <hr>

  <table class="table">
    <thead>
      <tr>
        <th>From</th>
        <th>Donation Amount</th>
        <th>Received</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render @funds %>
    </tbody>
  </table>
        <center>
            <%= will_paginate @funds %>
        </center>
</div>

<% end %>

app/views/funds/new.html.erb
<% provide(:title, 'Make A Donation') %>

<div class="hero-unit">
  <h1><%= yield(:title) %></h1>
  <hr>

<%= render 'form' %>
<hr>
<%= render 'back' %>


</div>

app/views/funds/show.html.erb
<% if user_signed_in? && current_user.admin? %>
<% provide(:title, 'Donation Received') %>

<div class="hero-unit">
  <h1><%= yield(:title) %></h1>
  <hr>
  
  <p>
  <strong>From:</strong>
  <%= @fund.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fund.email %>
</p>

<p>
  <strong>Dollars:</strong>
  <%= number_to_currency(@fund.dollars) %>
</p>

<p>
	  <strong>Received: </strong>
		<% t = @fund.created_at %>
    	<% t -= (7 * 60 * 60) %>
    	<%= t.strftime("%B %d, %Y @ %I:%M %p") %>
</p>
<hr>
<%= link_to 'Confirm Payment', edit_fund_path(@fund), class: "btn btn-success btn-large" %><br>
<p>
<%= link_to '<< Back', funds_path, class: "btn btn-inverse" %>
</p>
</div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li><%= link_to 'John For Carlos',  root_path, class: "brand" %></li>

                        <% if user_signed_in? && current_user.admin? %>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Donations
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">                                
                                    <li><%= link_to "Manage Donations", funds_path %></li>
                                    <li><%= link_to "New Donation", new_fund_path %></li>
                                </ul>
                            </li>
                        <% else %>
                            <li><%= link_to 'Donations', new_fund_path %></li>
                        <% end %>
                        <li><%= link_to 'Messages', messages_path %></li>
                    </ul>

                    <ul class="nav pull-right">
                        <% if user_signed_in? %>
                            <li><%= link_to 'Log Out',  destroy_user_session_path, method: :delete %></li>
                        <% end %>
                        <li><%= link_to 'Admin',  new_user_session_path %></li>
                    </ul>

                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>John For Carlos | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
	    <%= yield %>
	</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>John For Carlos | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
  <%= csrf_meta_tags %>
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container well">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>


	<div class="hero-unit">
		<center>
		<h1>John For Carlos</h1><hr>
		</center>
		<div class="row">
			<div class="span4">
				<center>
					<img src="http://s3.amazonaws.com/viadeca/receipts/images/000/000/003/original/mom_and_dad.jpg?1383691640" width="400" style="border: 0px solid #000000" />
					<hr>
					<%= link_to "Make A Donation", new_fund_path, class: "btn btn-primary btn-large" %>

					<%= link_to "Leave A Message", messages_path, class: "btn btn-primary btn-large" %>
				</center>
			</div>
			<div class="span6">
				<p>
					John Williams Iason, beloved husband to Valorie, cherished father to Scott and Liz, adored father-in-law to Ali and Teo, and the sweetest pops to Drew and Kate passed away on Monday, October 28, 2013 surrounded by the love from Valorie, Scott and Liz. He will be greatly missed and forever a part of all of our lives. John had a great love for children and for the past two years has mentored a little boy named Carlos (now 9 years old) through the Chatham County Together program whose mission is to mentor and guide children and youth to help them reach their full potential and become healthy, positive members of their communities.
				</p>
				<p>

					Beyond tutoring, John and Carlos also played tennis, went swimming, golfed, enjoyed movies, went trick or treating together and shared many meals together - always with an ice cream dessert. When seen together it was clear how meaningful their time together was for both of them.
				</p>
				<p>
					We have all been so touched by the support from our family and friends and ask that in lieu of flowers and gifts, that you donate to Carlos’ educational fund.
				</p>
				<p>
					Thank you very much,
				</p>
				<p>
					The Iasons
				</p>
			</div>
		</div>
		<center>
</center>
	</div>

app/views/pins/_back.html.erb
<p><%= link_to '<< Back', messages_path, class: "btn btn-inverse" %></p>

app/views/pins/_edit.html.erb
<p><%= link_to 'Edit Message', edit_pin_path(@pin), class: "btn btn-success"  %></p>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, label: "Message", :input_html => { :rows => 5, :placeholder => "Please leave your message here for others to see", :class => "span9"} %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add Message", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
      <tr>
        <td>
        	<em>"<%=pin.description%>"</em> <br>
        	<strong>-<%= pin.name %></strong>
        	<% t = pin.created_at %>
        	<% t -= (7 * 60 * 60) %>
        	<p style="font-size: .5em"><%= t.strftime("%B %d, %Y @ %I:%M %p") %> </p>
        </td>

        <% if user_signed_in? && current_user.admin? %>
	        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	    <% else %>
	    	<td></td>
	    <% end %>
      </tr>

app/views/pins/edit.html.erb
<% provide(:title, 'Edit Message') %>

<div class="hero-unit">
  <h1><%= yield(:title) %></h1>

<%= render 'form' %>

<%= render 'back' %>
</div>

app/views/pins/index.html.erb
<% provide(:title, 'Messages') %>

<div class="hero-unit">
  <h2 align="center"><%= yield(:title) %></h2>
  <div class="row">
    <div class="span9 offset1">

        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <%= render @pins %>
          </tbody>
        </table>
        <center>
            <%= will_paginate @pins %>
        </center>
    </div>
  </div>
</div>
<center>
  <%= link_to 'Add Message', new_pin_path, class: "btn btn-large" %><br>
</center>

app/views/pins/new.html.erb
<% provide(:title, 'Leave A Message') %>

<div class="hero-unit">
<h1><%= yield(:title) %></h1>
<hr>
<%= render 'form' %>
<hr>
<%= render 'back' %>
</div>

app/views/pins/show.html.erb
<% provide(:title, 'Message Added') %>

<div class="hero-unit">
  <h1><%= yield(:title) %></h1><hr>

<p>
  <strong>From:</strong>
  <%= @pin.name %>
</p>

  <em><%= @pin.description %></em>

<%= render 'edit' %>
<%= render 'back' %>


</div>